### ISSUE TITLE
Add `Hot Module Replacement` to increase developer adoption

### ISSUE THREAD

**Issue by heybran** [EvolvedWeb/evowc#27]
I don't think this is an easy task and a priority for now, but for brainstorming, I think `evowc` should be adding `Hot Module Replacement` feature so developers don't need to run `npm run evowc` each time they update their components.

## The Ideal Development Flow?

1. Developers run `npm run dev`.
2. Add a new component at `./src/components/MyButton.html`
3. Add `my-button` to `index.html` page
4. With `Home Module Replacement` browser will reload to pick up the new changes.
5. Go back to `./src/components/MyButton.html` and update components, browser UI updates as well.

And then for the production build, run `npm run evowc` to get everything ready for production.

**Comment by intervalia** [comment]
This is planned and will be done in steps.

1. Create a way for evowc to monitor the source folder and compile all changes as they happen.
2. Modify the sample server and client code to know when changes have been made and refresh the browser

Step 2 will be optional. If you don't want auto-refresh then you don't get it. If you do want it then you get it.
